import React, { useState } from "react";
import { Movie } from "../types";
import { 
  X, 
  Download, 
  Play, 
  Copy, 
  Check, 
  FileText, 
  Info, 
  Sparkles, 
  Film, 
  ExternalLink,
  ShieldCheck,
  Tv,
  HelpCircle
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import PosterFallback from "./PosterFallback";

interface DownloadModalProps {
  movie: Movie;
  onClose: () => void;
  onStream: (movie: Movie) => void;
}

export default function DownloadModal({ movie, onClose, onStream }: DownloadModalProps) {
  const [copiedIndex, setCopiedIndex] = useState<number | null>(null);
  const [sampleDownloading, setSampleDownloading] = useState(false);

  const tmdbId = movie.tmdbId || (movie.id.startsWith("tt") ? "" : movie.id);
  const imdbId = movie.imdbId || (movie.id.startsWith("tt") ? movie.id : "");

  // Major HD Stream Server URLs for this movie
  const streamServers = [
    {
      name: "VidSrc.cc HD Server",
      url: `https://vidsrc.cc/v2/embed/movie/${tmdbId || movie.id}`,
      badge: "Fast 1080p",
      rec: "Best for IDM / 1DM capture"
    },
    {
      name: "Embed.su Server",
      url: `https://embed.su/embed/movie/${tmdbId || movie.id}`,
      badge: "Auto Subs",
      rec: "Multi-language subtitles"
    },
    {
      name: "VidSrc Pro 4K",
      url: `https://vidsrc.pro/embed/movie/${tmdbId || movie.id}`,
      badge: "4K HD",
      rec: "High Bitrate Stream"
    }
  ];

  const handleCopyUrl = (url: string, index: number) => {
    navigator.clipboard.writeText(url);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2500);
  };

  // Download .NFO Movie Metadata package
  const handleDownloadNfo = () => {
    const fileContent = `=====================================================
BFLIX CINEMA STREAMING - OFFICIAL MOVIE METADATA PACKAGE
=====================================================
Title       : ${movie.title}
Year        : ${movie.year}
Rating      : ⭐ ${movie.imdbRating} / 10
Genres      : ${movie.genres.join(", ")}
TMDB ID     : ${tmdbId || "N/A"}
IMDb ID     : ${imdbId || "N/A"}

SYNOPSIS:
${movie.plot}

STREAMING SERVERS & M3U8 SOURCES:
1. VidSrc.cc : https://vidsrc.cc/v2/embed/movie/${tmdbId || movie.id}
2. Embed.su  : https://embed.su/embed/movie/${tmdbId || movie.id}
3. VidSrc.pro: https://vidsrc.pro/embed/movie/${tmdbId || movie.id}

HOW TO DOWNLOAD / WATCH FULL MOVIE:
1. Copy any stream URL above into VLC Media Player (Media -> Open Network Stream).
2. Or use Internet Download Manager (IDM), 1DM, or JDownloader to snag the video stream.
3. Or play directly inside BFLIX using the built-in player.

Generated by BFLIX Cinema Stream.
=====================================================`;

    const blob = new Blob([fileContent], { type: "text/plain;charset=utf-8" });
    const blobUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = blobUrl;
    a.download = `${movie.title.replace(/[^a-zA-Z0-9]/g, "_")}_Metadata.nfo`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(blobUrl), 10000);
  };

  // Download sample test MP4 file (clearly labeled as a test clip)
  const handleDownloadSampleMp4 = () => {
    setSampleDownloading(true);
    const sampleMp4Url = "https://vjs.zencdn.net/v/oceans.mp4";
    const fileName = `${movie.title.replace(/[^a-zA-Z0-9]/g, "_")}_Sample_Clip.mp4`;

    const a = document.createElement("a");
    a.href = sampleMp4Url;
    a.target = "_blank";
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);

    setTimeout(() => setSampleDownloading(false), 2000);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 overflow-y-auto bg-black/92 backdrop-blur-xl flex items-center justify-center p-3 sm:p-6">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 15 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 15 }}
          transition={{ type: "spring", duration: 0.4 }}
          className="relative bg-[#0a0a0c] border border-white/10 rounded-3xl w-full max-w-2xl overflow-hidden shadow-2xl flex flex-col my-auto"
        >
          {/* Header */}
          <div className="bg-[#121215] border-b border-white/10 px-6 py-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-imdb/10 border border-imdb/30 text-imdb rounded-xl">
                <Download className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-white font-bold text-base tracking-tight">
                  Download & Stream Options
                </h3>
                <p className="text-xs text-gray-400 font-mono">
                  {movie.title} ({movie.year})
                </p>
              </div>
            </div>

            <button
              onClick={onClose}
              className="p-2 bg-white/5 hover:bg-red-500/20 hover:border-red-500/30 border border-white/10 rounded-full text-white transition-all cursor-pointer"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="p-6 space-y-6 max-h-[80vh] overflow-y-auto">
            {/* Movie Header Card */}
            <div className="flex items-center gap-4 p-4 rounded-2xl bg-white/[0.03] border border-white/10">
              <div className="w-16 h-22 rounded-xl overflow-hidden shrink-0 shadow-lg relative bg-gray-900">
                <img
                  src={movie.poster}
                  alt={movie.title}
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    e.currentTarget.style.display = "none";
                  }}
                />
              </div>
              <div className="space-y-1">
                <h4 className="text-white font-bold text-lg leading-snug">{movie.title}</h4>
                <div className="flex items-center gap-2 text-xs text-gray-400 font-mono">
                  <span className="text-amber-400 font-bold">⭐ {movie.imdbRating}</span>
                  <span>•</span>
                  <span>{movie.year}</span>
                  {movie.genres?.length > 0 && (
                    <>
                      <span>•</span>
                      <span>{movie.genres.slice(0, 2).join(", ")}</span>
                    </>
                  )}
                </div>
                <p className="text-xs text-gray-400 line-clamp-2 pt-1">{movie.plot}</p>
              </div>
            </div>

            {/* Explanation Callout */}
            <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-500/20 flex gap-3 text-xs text-amber-200/90 leading-relaxed">
              <Info className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
              <div>
                <p className="font-bold text-amber-300">How Full Movie Downloading Works</p>
                <p className="text-[11px] text-amber-200/80 mt-1">
                  Full copyrighted feature films (1–3 hours) are served via secure HLS video streams. To watch or save the full movie, use our built-in player or copy the stream URL below into Internet Download Manager (IDM), 1DM, or VLC.
                </p>
              </div>
            </div>

            {/* ACTION 1: Watch Full Movie Stream (Primary) */}
            <div className="space-y-2">
              <span className="text-xs font-bold text-gray-300 uppercase tracking-wider font-mono flex items-center gap-1.5">
                <Play className="w-3.5 h-3.5 text-imdb fill-imdb" />
                <span>Option 1: Stream Full Movie (Recommended)</span>
              </span>
              <button
                onClick={() => {
                  onClose();
                  onStream(movie);
                }}
                className="w-full py-3.5 px-5 bg-imdb hover:bg-imdb-hover text-black font-extrabold rounded-2xl text-sm flex items-center justify-center gap-2 transition-all shadow-lg shadow-imdb/10 cursor-pointer"
              >
                <Play className="w-4 h-4 fill-black" />
                <span>Play Full Movie Now (9 HD Servers)</span>
              </button>
            </div>

            {/* ACTION 2: Copy Stream Links for Downloader Apps (IDM, VLC, 1DM) */}
            <div className="space-y-3">
              <span className="text-xs font-bold text-gray-300 uppercase tracking-wider font-mono flex items-center gap-1.5">
                <ExternalLink className="w-3.5 h-3.5 text-imdb" />
                <span>Option 2: Capture Stream with Downloader (IDM / 1DM / VLC)</span>
              </span>

              <div className="space-y-2">
                {streamServers.map((server, index) => (
                  <div
                    key={index}
                    className="p-3 bg-white/[0.03] border border-white/10 rounded-xl flex items-center justify-between gap-3 text-xs"
                  >
                    <div className="space-y-0.5 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-white">{server.name}</span>
                        <span className="px-1.5 py-0.5 bg-amber-500/10 text-amber-400 border border-amber-500/20 text-[10px] font-mono font-bold rounded">
                          {server.badge}
                        </span>
                      </div>
                      <p className="text-[11px] text-gray-400 font-mono truncate">{server.url}</p>
                    </div>

                    <button
                      onClick={() => handleCopyUrl(server.url, index)}
                      className="px-3 py-2 bg-white/10 hover:bg-white/20 border border-white/10 text-white font-semibold rounded-lg text-xs flex items-center gap-1.5 shrink-0 transition-all cursor-pointer"
                    >
                      {copiedIndex === index ? (
                        <>
                          <Check className="w-3.5 h-3.5 text-emerald-400" />
                          <span className="text-emerald-400">Copied!</span>
                        </>
                      ) : (
                        <>
                          <Copy className="w-3.5 h-3.5 text-imdb" />
                          <span>Copy URL</span>
                        </>
                      )}
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* ACTION 3: Additional Offline Files */}
            <div className="space-y-3 pt-2 border-t border-white/10">
              <span className="text-xs font-bold text-gray-300 uppercase tracking-wider font-mono flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5 text-imdb" />
                <span>Option 3: Download Packages & Sample Clips</span>
              </span>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                {/* Download Metadata Package */}
                <button
                  onClick={handleDownloadNfo}
                  className="p-3.5 bg-white/[0.03] hover:bg-white/[0.08] border border-white/10 rounded-xl text-left flex items-start gap-3 transition-all cursor-pointer group"
                >
                  <div className="p-2 bg-imdb/10 border border-imdb/20 text-imdb rounded-lg group-hover:bg-imdb group-hover:text-black transition-all">
                    <FileText className="w-4 h-4" />
                  </div>
                  <div>
                    <p className="text-xs font-bold text-white">Save .NFO Metadata</p>
                    <p className="text-[11px] text-gray-400">Download movie details & all server URLs package.</p>
                  </div>
                </button>

                {/* Download Sample Video Clip */}
                <button
                  onClick={handleDownloadSampleMp4}
                  className="p-3.5 bg-white/[0.03] hover:bg-white/[0.08] border border-white/10 rounded-xl text-left flex items-start gap-3 transition-all cursor-pointer group"
                >
                  <div className="p-2 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-lg group-hover:bg-emerald-500 group-hover:text-black transition-all">
                    <Download className="w-4 h-4" />
                  </div>
                  <div>
                    <p className="text-xs font-bold text-white">Sample Video Clip (.mp4)</p>
                    <p className="text-[11px] text-gray-400">Short test MP4 clip to verify player playback.</p>
                  </div>
                </button>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}
